CODING_METHOD = 'DESIGNED_CODE'
DESIGNED_CODE = CODING_METHOD == 'DESIGNED_CODE'

EXPEND = 3
FILTER = True

BITS_NUM = 10
FRAME_RATE = 240
MOUSE_FRAME_RATE = 1600 #2800 # 2400

PREAMBLE_LIST = [1, -1, 1, -1]
PREAMBLE_PATTERN = '1010'
import numpy as np
PREAMBLE_NP = np.array(PREAMBLE_LIST)
SIZE = (32, 32) # (256, 256)
CRC_LEN = 4

# setting for decoder

CHECK_BIT = 'BY_TIME' # 'BY_PERCENTAGE'
FRAMES_PER_SECOND_AFTER_INTERPOLATE = 9600
INTERPOLATION_INTERVAL = 0.08 # 0.5
END_INTERVAL = 0.1
# EXTRA_LEN = 0.02
EXTRA_LEN = END_INTERVAL - INTERPOLATION_INTERVAL

MEAN_WIDTH = 40 # 50

POINTS_TO_COMBINE = FRAMES_PER_SECOND_AFTER_INTERPOLATE / FRAME_RATE / 10 # 5 for advanced interpolation, 40 for 20hz , 14 for 60hz -> maintain 10 points for one bit
assert int(POINTS_TO_COMBINE) == POINTS_TO_COMBINE
